//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string InitialsLanguage { get; set; }
        public Nullable<int> IdLanguage { get; set; }
        public string DotNetCulture { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
