//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalParameters
    {
        public OptionalParameters()
        {
            this.Users_OptionalParameters = new HashSet<Users_OptionalParameters>();
        }
    
        public System.Guid ID { get; set; }
        public string Parameter { get; set; }
        public byte[] Value { get; set; }
        public string TypeOfValue { get; set; }
    
        public virtual ICollection<Users_OptionalParameters> Users_OptionalParameters { get; set; }
    }
}
