//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedirectAccessRequests
    {
        public System.Guid RequestID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
