//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Roles_Users = new HashSet<Roles_Users>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string HomePage { get; set; }
    
        public virtual ICollection<Roles_Users> Roles_Users { get; set; }
    }
}
