//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserManagerEntities : DbContext
    {
        public UserManagerEntities()
            : base("name=UserManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuditLogin> AuditLogin { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Groups_Users> Groups_Users { get; set; }
        public DbSet<Languages> Languages { get; set; }
        public DbSet<RedirectAccessRequests> RedirectAccessRequests { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Roles_Users> Roles_Users { get; set; }
        public DbSet<Users_OptionalParameters> Users_OptionalParameters { get; set; }
        public DbSet<vw_UserInfo> vw_UserInfo { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<OptionalParameters> OptionalParameters { get; set; }
    }
}
