//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AuditLogin = new HashSet<AuditLogin>();
            this.Groups_Users = new HashSet<Groups_Users>();
            this.RedirectAccessRequests = new HashSet<RedirectAccessRequests>();
            this.Roles_Users = new HashSet<Roles_Users>();
            this.Users_OptionalParameters = new HashSet<Users_OptionalParameters>();
        }
    
        public System.Guid ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public string Email { get; set; }
        public string DefaultHomePage { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Domain { get; set; }
        public Nullable<System.DateTime> LastDateUpdatePassword { get; set; }
    
        public virtual ICollection<AuditLogin> AuditLogin { get; set; }
        public virtual ICollection<Groups_Users> Groups_Users { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual ICollection<RedirectAccessRequests> RedirectAccessRequests { get; set; }
        public virtual ICollection<Roles_Users> Roles_Users { get; set; }
        public virtual ICollection<Users_OptionalParameters> Users_OptionalParameters { get; set; }
    }
}
