//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogin
    {
        public Nullable<System.Guid> UserID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public Nullable<bool> Accessed { get; set; }
        public string MessageInfo { get; set; }
        public string IP { get; set; }
        public string Username { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
