//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMachineNotification
    {
        public int IdMessageMachine { get; set; }
        public string UserId { get; set; }
        public System.DateTime ReadingDate { get; set; }
    
        public virtual MessageMachine MessageMachine { get; set; }
    }
}
