//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTranslation
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int MessageLanguageId { get; set; }
        public string Translation { get; set; }
    
        public virtual MessageLanguages MessageLanguages { get; set; }
        public virtual MessagesIndex MessagesIndex { get; set; }
    }
}
