//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterResetValue
    {
        public int Id { get; set; }
        public int ParameterMachineId { get; set; }
        public System.DateTime ResetDate { get; set; }
        public Nullable<decimal> ResetValue { get; set; }
        public Nullable<decimal> ValueBeforeReset { get; set; }
        public Nullable<int> MachineId { get; set; }
    
        public virtual ParameterMachine ParameterMachine { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
