//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMachineMapping
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int MachineId { get; set; }
        public string TimeZone { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Users Users { get; set; }
    }
}
