/*
Deployment script for LOLATEST

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "LOLATEST"
:setvar DefaultFilePrefix "LOLATEST"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Table [dbo].[Spindle] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Spindle])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[DF__spindle__Replace__6AEFE058]...';


GO
ALTER TABLE [dbo].[Spindle] DROP CONSTRAINT [DF__spindle__Replace__6AEFE058];


GO
PRINT N'Dropping [dbo].[DF__spindle__ToolCha__6BE40491]...';


GO
ALTER TABLE [dbo].[Spindle] DROP CONSTRAINT [DF__spindle__ToolCha__6BE40491];


GO
PRINT N'Dropping [dbo].[FK_Spindle_Machine]...';


GO
ALTER TABLE [dbo].[Spindle] DROP CONSTRAINT [FK_Spindle_Machine];


GO
PRINT N'Dropping [dbo].[Spindle]...';


GO
DROP TABLE [dbo].[Spindle];


GO
PRINT N'Altering [dbo].[CurrentState]...';


GO
ALTER TABLE [dbo].[CurrentState]
    ADD [ResidueWorkingTime] BIGINT NULL;


GO
PRINT N'Altering [dbo].[MessageMachine]...';


GO
ALTER TABLE [dbo].[MessageMachine]
    ADD [UserId] NVARCHAR (200) NULL;


GO
PRINT N'Altering [api].[usp_HistoricizingStates]...';


GO
-- =============================================
-- Author:		Marco Servillo, Alten Italia
-- Create date:	2017-12-05
-- Description:	Storicizzazione giornaliera tabella State
-- =============================================
ALTER PROCEDURE [api].[usp_HistoricizingStates](@machineId INT)
AS
         BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
             SET NOCOUNT ON;
             DECLARE @date DATETIME;
	    
/**/

             SELECT @date = isnull(MAX(day), 0)
             FROM [HistoryState]
             WHERE MachineId = @machineId;
    
/* DAY AGGREGATION */

             WITH CompleteHistoryState
                  AS (SELECT CAST(StateMachine.Day AS DATE) Day,
                             0 AS ElapsedTime,
                             MachineId,
                             StateMachine.Operator,
                             IIF(State.Id = 1, 0, NULL) AS OverfeedAvg,
                             StateMachine.Shift,
                             (DATEPART(year, CAST(StateMachine.Day AS DATE)) * 10000) + (DATEPART(month, CAST(StateMachine.Day AS DATE)) * 100) + DATEPART(day, CAST(StateMachine.Day AS DATE)) AS Period,
                             State.Id AS StateId,
                             'd' AS TypeHistory
                      FROM dbo.StateMachine
                           CROSS JOIN State
                      WHERE MachineId = @machineId-- AND CAST(StateMachine.Day AS DATE) >= @date
                             
                      GROUP BY CAST(StateMachine.Day AS DATE),
                               MachineId,
                               CUBE(StateMachine.Operator, StateMachine.Shift),
                               State.Id)
                  MERGE [dbo].[HistoryState] AS target
                  USING
(
    SELECT ISNULL(b.Day, a.Day) Day,
           IIF(b.Day IS NOT NULL, b.ElapsedTime, a.ElapsedTime) ElapsedTime,
           IIF(b.Day IS NOT NULL, b.MachineId, a.MachineId) MachineId,
           IIF(b.Day IS NOT NULL, b.Operator, a.Operator) Operator,
           IIF(b.Day IS NOT NULL, b.OverfeedAvg, a.OverfeedAvg) OverfeedAvg,
           IIF(b.Day IS NOT NULL, b.Shift, a.Shift) Shift,
           IIF(b.Day IS NOT NULL, b.Period, a.Period) Period,
           IIF(b.Day IS NOT NULL, b.StateId, a.StateId) StateId,
           IIF(b.Day IS NOT NULL, b.TypeHistory, a.TypeHistory) TypeHistory
    FROM CompleteHistoryState a
         LEFT JOIN
(
    SELECT CAST(StateMachine.Day AS DATE) Day,
           SUM(StateMachine.ElapsedTime) AS ElapsedTime,
           MachineId,
           StateMachine.Operator,
		 IIF(StateId = 1, IIF(SUM(ElapsedTime) > 0, SUM(Overfeed * ElapsedTime) / SUM(ElapsedTime), 0), NULL) AS OverfeedAvg,
           StateMachine.Shift,
           (DATEPART(year, CAST(StateMachine.Day AS DATE)) * 10000) + (DATEPART(month, CAST(StateMachine.Day AS DATE)) * 100) + DATEPART(day, CAST(StateMachine.Day AS DATE)) AS Period,
           StateId,
           'd' AS TypeHistory
    FROM dbo.StateMachine
    WHERE MachineId = @machineId-- AND CAST(StateMachine.Day AS DATE) >= @date
    GROUP BY CAST(StateMachine.Day AS DATE),
             MachineId,
             CUBE(StateMachine.Operator, StateMachine.Shift),
             StateId
) b ON a.Day = b.Day
       AND a.MachineId = b.MachineId
       AND (a.Operator = b.Operator
            OR (a.Operator IS NULL
                AND b.Operator IS NULL))
       AND (a.Shift = b.Shift
            OR (a.Shift IS NULL
                AND b.Shift IS NULL))
       AND a.StateId = b.StateId
) AS source
ON target.Day = source.Day
   AND target.MachineId = source.MachineId
   AND (target.Operator = source.Operator
        OR (target.Operator IS NULL
            AND source.operator IS NULL))
   AND (target.Shift = source.Shift
        OR (target.Shift IS NULL
            AND source.Shift IS NULL))
   AND target.StateId = source.StateId
   AND target.TypeHistory = source.TypeHistory
                      WHEN MATCHED
                      THEN UPDATE SET
                                      target.ElapsedTime = source.ElapsedTime,
                                      target.OverfeedAvg = source.OverfeedAvg
                      WHEN NOT MATCHED BY TARGET
                      THEN
                        INSERT(Day,
                               ElapsedTime,
                               MachineId,
                               Operator,
                               OverfeedAvg,
                               Period,
                               Shift,
                               StateId,
                               TypeHistory)
                        VALUES
(Day,
 ElapsedTime,
 MachineId,
 Operator,
 OverfeedAvg,
 Period,
 Shift,
 StateId,
 TypeHistory
);

/**/

         END;
GO
PRINT N'Refreshing [dbo].[usp_CleanMachineData]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[usp_CleanMachineData]';


GO
PRINT N'Refreshing [dbo].[usp_MesUserMachines]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[usp_MesUserMachines]';


GO
PRINT N'Refreshing [log].[usp_UpdateAllRecordsDemo]...';


GO
EXECUTE sp_refreshsqlmodule N'[log].[usp_UpdateAllRecordsDemo]';


GO
PRINT N'Refreshing [log].[usp_UpdateDateMes]...';


GO
EXECUTE sp_refreshsqlmodule N'[log].[usp_UpdateDateMes]';


GO
PRINT N'Refreshing [api].[usp_HistoricizingMessages]...';


GO
EXECUTE sp_refreshsqlmodule N'[api].[usp_HistoricizingMessages]';


GO
PRINT N'Refreshing [api].[usp_HistoricizingAll]...';


GO
EXECUTE sp_refreshsqlmodule N'[api].[usp_HistoricizingAll]';


GO
PRINT N'Update complete.';


GO
