//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL_SQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FST_FomMonitoringSQLiteEntities : DbContext
    {
        public FST_FomMonitoringSQLiteEntities()
            : base("name=FST_FomMonitoringSQLiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<error> error { get; set; }
        public virtual DbSet<historyAlarm> historyAlarm { get; set; }
        public virtual DbSet<historyJob> historyJob { get; set; }
        public virtual DbSet<historyPiece> historyPiece { get; set; }
        public virtual DbSet<historyState> historyState { get; set; }
        public virtual DbSet<info> info { get; set; }
        public virtual DbSet<piece> piece { get; set; }
        public virtual DbSet<state> state { get; set; }
        public virtual DbSet<tool> tool { get; set; }
        public virtual DbSet<historyBar> historyBar { get; set; }
        public virtual DbSet<spindle> spindle { get; set; }
        public virtual DbSet<bar> bar { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<historyMessage> historyMessage { get; set; }
    }
}
