//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class historyBar
    {
        public int Id { get; set; }
        public string System { get; set; }
        public Nullable<double> BarLengthSum { get; set; }
        public Nullable<int> OffCutCount { get; set; }
        public Nullable<int> OffcutLengthSum { get; set; }
        public Nullable<int> BarCount { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<long> ElapsedTime { get; set; }
        public Nullable<long> ElapsedTimeProducing { get; set; }
    }
}
