//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int Id { get; set; }
        public string KeyId { get; set; }
        public string MachineSerial { get; set; }
        public string MachineType { get; set; }
        public string MachineModel { get; set; }
        public string MachineDescription { get; set; }
        public string Product { get; set; }
        public string ProductVersion { get; set; }
        public string FirmwareVersion { get; set; }
        public string PlcVersion { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string PlantName { get; set; }
        public string PlantAddress { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> NextMaintenanceService { get; set; }
        public Nullable<double> StateProductivityGreenThreshold { get; set; }
        public Nullable<double> StateProductivityYellowThreshold { get; set; }
        public Nullable<double> PiecesProductivityGreenThreshold { get; set; }
        public Nullable<double> PiecesProductivityYellowThreshold { get; set; }
        public Nullable<double> BarsProductivityGreenThreshold { get; set; }
        public Nullable<double> BarsProductivityYellowThreshold { get; set; }
        public Nullable<double> OverfeedGreenThreshold { get; set; }
        public Nullable<double> OverfeedYellowThreshold { get; set; }
        public Nullable<int> Shift1StartHour { get; set; }
        public Nullable<int> Shift1StartMinute { get; set; }
        public Nullable<int> Shift2StartHour { get; set; }
        public Nullable<int> Shift2StartMinute { get; set; }
        public Nullable<int> Shift3StartHour { get; set; }
        public Nullable<int> Shift3StartMinute { get; set; }
        public Nullable<double> UTC { get; set; }
    }
}
