//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class spindle
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<long> ExpectedWorkTime { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> WorkTotalTime { get; set; }
        public Nullable<long> Work3KTime { get; set; }
        public Nullable<long> Work6KTime { get; set; }
        public Nullable<long> Work9KTime { get; set; }
        public Nullable<long> Work12KTime { get; set; }
        public Nullable<long> Work15KTime { get; set; }
        public Nullable<long> Work18KTime { get; set; }
        public Nullable<int> WorkOverheatingEvents { get; set; }
        public Nullable<int> WorkOverPowerEvents { get; set; }
        public Nullable<int> WorkOverVibratingEvents { get; set; }
        public Nullable<System.DateTime> Replaced { get; set; }
        public Nullable<int> ToolChangedCount { get; set; }
        public string Serial { get; set; }
    }
}
