//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<long> TimeSpanDuration { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> Overfeed { get; set; }
        public Nullable<int> State1 { get; set; }
        public string Reason { get; set; }
        public string Operator { get; set; }
        public Nullable<int> OperatorLevel { get; set; }
    }
}
