//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FomMonitoringResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plant.
        /// </summary>
        public static string AddPlant {
            get {
                return ResourceManager.GetString("AddPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms number.
        /// </summary>
        public static string AlarmsNumber {
            get {
                return ResourceManager.GetString("AlarmsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyLabel {
            get {
                return ResourceManager.GetString("ApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Speed.
        /// </summary>
        public static string AverageSpeed {
            get {
                return ResourceManager.GetString("AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assi.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors/Axes.
        /// </summary>
        public static string AxisMotors {
            get {
                return ResourceManager.GetString("AxisMotors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking.
        /// </summary>
        public static string Breaking {
            get {
                return ResourceManager.GetString("Breaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string ChangePasswordSuccessfully {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, come back.
        /// </summary>
        public static string ComeBack {
            get {
                return ResourceManager.GetString("ComeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Completion {
            get {
                return ResourceManager.GetString("Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama &lt;br /&gt; totali.
        /// </summary>
        public static string Contat_Tagli_TF {
            get {
                return ResourceManager.GetString("Contat_Tagli_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama &lt;br /&gt; totali.
        /// </summary>
        public static string Contat_Tagli_TM {
            get {
                return ResourceManager.GetString("Contat_Tagli_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created.
        /// </summary>
        public static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E’ stata generata una nuova utenza di tipo [TIPO_USER], di seguito le credenziali: &lt;br/&gt; utente: [USERNAME] &lt;br/&gt;password: [PASSWORD] provvisoria generata. &lt;br/&gt; La password andrà resettata obbligatoriamente al primo accesso in LOLA.
        /// </summary>
        public static string CreateUserEmailBody {
            get {
                return ResourceManager.GetString("CreateUserEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOLA - Credenziali nuovo utente:.
        /// </summary>
        public static string CreateUserEmailSubject {
            get {
                return ResourceManager.GetString("CreateUserEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. spegnimenti&lt;br /&gt;critici &lt;br/&gt; motore lama TF.
        /// </summary>
        public static string Critic_LamaOff_TF {
            get {
                return ResourceManager.GetString("Critic_LamaOff_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. spegnimenti&lt;br /&gt;critici &lt;br/&gt; motore lama TM.
        /// </summary>
        public static string Critic_LamaOff_TM {
            get {
                return ResourceManager.GetString("Critic_LamaOff_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range.
        /// </summary>
        public static string CustomRangeLabel {
            get {
                return ResourceManager.GetString("CustomRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutoff.
        /// </summary>
        public static string Cutoff {
            get {
                return ResourceManager.GetString("Cutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this user?.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User disabled.
        /// </summary>
        public static string DisableUser {
            get {
                return ResourceManager.GetString("DisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOLA has been optimised for mobile usage. &lt;br /&gt;For a list of devices, please see the section &lt;br /&gt;&quot;Terms &amp; Conditions&quot;. .
        /// </summary>
        public static string DisclaimerLogin {
            get {
                return ResourceManager.GetString("DisclaimerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOLA has been optimised for mobile usage on the following devices: Samsung S10, Apple IPhone X, Samsung Galaxy S7, Apple IPhone 8, Apple IPad PRO, Apple IPad 2. Web browsers: Google Chrome for Windows and Safari for MAC.&quot;.
        /// </summary>
        public static string DisclaimerMobileDevices {
            get {
                return ResourceManager.GetString("DisclaimerMobileDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string Disclamer {
            get {
                return ResourceManager.GetString("Disclamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;H4&gt;DISCLAIMER&lt;/H4&gt;&lt;p&gt;The data acquired by Fom Industrie s.r.l. using the LO.LA application will be stored and handled for statistical purposes only, and will not be passed on to third parties. As this is not personal information, it is not subject to the contents of EU Regulation 2016/679.
        ///&lt;br&gt;&lt;br&gt;
        ///Customers are informed that the reliability of the statistics obtained from the data collected (need for periodic and/or special maintenance, wear in components such as electrospindles, tools, mechanical and/o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DisclamerBody {
            get {
                return ResourceManager.GetString("DisclamerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User enabled.
        /// </summary>
        public static string EnableUser {
            get {
                return ResourceManager.GetString("EnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter passwords.
        /// </summary>
        public static string EnterPasswords {
            get {
                return ResourceManager.GetString("EnterPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error States.
        /// </summary>
        public static string ErrorStates {
            get {
                return ResourceManager.GetString("ErrorStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testa Fissa.
        /// </summary>
        public static string FixedHead {
            get {
                return ResourceManager.GetString("FixedHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Time.
        /// </summary>
        public static string GrossTime {
            get {
                return ResourceManager.GetString("GrossTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeadWorkshop.
        /// </summary>
        public static string HeadWorkshop {
            get {
                return ResourceManager.GetString("HeadWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        public static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous password.
        /// </summary>
        public static string LastPassword {
            get {
                return ResourceManager.GetString("LastPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with access.
        /// </summary>
        public static string LoginProblem {
            get {
                return ResourceManager.GetString("LoginProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string Machines {
            get {
                return ResourceManager.GetString("Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine States.
        /// </summary>
        public static string MachineStates {
            get {
                return ResourceManager.GetString("MachineStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made.
        /// </summary>
        public static string Made {
            get {
                return ResourceManager.GetString("Made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testa Mobile.
        /// </summary>
        public static string MobileHead {
            get {
                return ResourceManager.GetString("MobileHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        public static string ModifyUser {
            get {
                return ResourceManager.GetString("ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed head blade motor.
        /// </summary>
        public static string motore_lama_TF {
            get {
                return ResourceManager.GetString("motore_lama_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile head blade motor.
        /// </summary>
        public static string motore_lama_TM {
            get {
                return ResourceManager.GetString("motore_lama_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motori.
        /// </summary>
        public static string Motors {
            get {
                return ResourceManager.GetString("Motors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string MsgExpiredTime {
            get {
                return ResourceManager.GetString("MsgExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Time.
        /// </summary>
        public static string NetTime {
            get {
                return ResourceManager.GetString("NetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not associated with any machine.
        /// </summary>
        public static string NoMachine {
            get {
                return ResourceManager.GetString("NoMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not associated with any plant.
        /// </summary>
        public static string NoPlant {
            get {
                return ResourceManager.GetString("NoPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available.
        /// </summary>
        public static string NoRecordsAvailable {
            get {
                return ResourceManager.GetString("NoRecordsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. accensioni/ &lt;br /&gt;spegnimenti &lt;br/&gt; motore lama TF.
        /// </summary>
        public static string Num_LamaON_TF {
            get {
                return ResourceManager.GetString("Num_LamaON_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. accensioni/ &lt;br /&gt;spegnimenti &lt;br/&gt; motore lama TM.
        /// </summary>
        public static string Num_LamaON_TM {
            get {
                return ResourceManager.GetString("Num_LamaON_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM axis U.
        /// </summary>
        public static string Num_mPercorsiAsseU {
            get {
                return ResourceManager.GetString("Num_mPercorsiAsseU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM axis W.
        /// </summary>
        public static string Num_mPercorsiAsseW {
            get {
                return ResourceManager.GetString("Num_mPercorsiAsseW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM asse X.
        /// </summary>
        public static string Num_mPercorsiAsseX {
            get {
                return ResourceManager.GetString("Num_mPercorsiAsseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM asse Y.
        /// </summary>
        public static string Num_mPercorsiAsseY {
            get {
                return ResourceManager.GetString("Num_mPercorsiAsseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM asse Z.
        /// </summary>
        public static string Num_mPercorsiAsseZ {
            get {
                return ResourceManager.GetString("Num_mPercorsiAsseZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama&lt;br /&gt; totali.
        /// </summary>
        public static string Num_Tagli_TF {
            get {
                return ResourceManager.GetString("Num_Tagli_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama&lt;br /&gt; totali.
        /// </summary>
        public static string Num_Tagli_TM {
            get {
                return ResourceManager.GetString("Num_Tagli_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore vita &lt;br /&gt; lama &lt;br /&gt; effettive.
        /// </summary>
        public static string Ore_vita_lama_ef {
            get {
                return ResourceManager.GetString("Ore_vita_lama_ef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhating.
        /// </summary>
        public static string Overhating {
            get {
                return ResourceManager.GetString("Overhating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overpower.
        /// </summary>
        public static string Overpower {
            get {
                return ResourceManager.GetString("Overpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string OverVibrating {
            get {
                return ResourceManager.GetString("OverVibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama&lt;br /&gt;parziali&lt;br/&gt;(da reset).
        /// </summary>
        public static string Parz_tagli_TF {
            get {
                return ResourceManager.GetString("Parz_tagli_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagli lama&lt;br /&gt;parziali&lt;br/&gt;(da reset).
        /// </summary>
        public static string Parz_tagli_TM {
            get {
                return ResourceManager.GetString("Parz_tagli_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string PassNotValid {
            get {
                return ResourceManager.GetString("PassNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and repeat new password do not match.
        /// </summary>
        public static string PasswordNotSame {
            get {
                return ResourceManager.GetString("PasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters.
        /// </summary>
        public static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is incorrect.
        /// </summary>
        public static string PasswordSamePrevious {
            get {
                return ResourceManager.GetString("PasswordSamePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 6 characters.
        /// </summary>
        public static string PasswordShort {
            get {
                return ResourceManager.GetString("PasswordShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not the same.
        /// </summary>
        public static string PasswordsNotSame {
            get {
                return ResourceManager.GetString("PasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully reseted.
        /// </summary>
        public static string PasswordSuccessfullyReseted {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic/Ordinary Maintenance.
        /// </summary>
        public static string PeriodicMaintenance {
            get {
                return ResourceManager.GetString("PeriodicMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        public static string Phases {
            get {
                return ResourceManager.GetString("Phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PlantAddress {
            get {
                return ResourceManager.GetString("PlantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant created successfully.
        /// </summary>
        public static string PlantCreated {
            get {
                return ResourceManager.GetString("PlantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string PlantCustomers {
            get {
                return ResourceManager.GetString("PlantCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this plant?.
        /// </summary>
        public static string PlantDelete {
            get {
                return ResourceManager.GetString("PlantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant deleted.
        /// </summary>
        public static string PlantDeleted {
            get {
                return ResourceManager.GetString("PlantDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant deleted successfully.
        /// </summary>
        public static string PlantDeletedConfirm {
            get {
                return ResourceManager.GetString("PlantDeletedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant cannot be deleted..
        /// </summary>
        public static string PlantImpossibileDeleted {
            get {
                return ResourceManager.GetString("PlantImpossibileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string PlantMachines {
            get {
                return ResourceManager.GetString("PlantMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Messages.
        /// </summary>
        public static string PlantMessages {
            get {
                return ResourceManager.GetString("PlantMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant modified successfully.
        /// </summary>
        public static string PlantModified {
            get {
                return ResourceManager.GetString("PlantModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant modify.
        /// </summary>
        public static string PlantModify {
            get {
                return ResourceManager.GetString("PlantModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlantName {
            get {
                return ResourceManager.GetString("PlantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        public static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redone.
        /// </summary>
        public static string Redone {
            get {
                return ResourceManager.GetString("Redone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        public static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset user&apos;s password?.
        /// </summary>
        public static string ResetUserPassword {
            get {
                return ResourceManager.GetString("ResetUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired or has been interrupted.
        /// </summary>
        public static string SessionTimeout {
            get {
                return ResourceManager.GetString("SessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        public static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Ranges.
        /// </summary>
        public static string SpeedRanges {
            get {
                return ResourceManager.GetString("SpeedRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multispindle.
        /// </summary>
        public static string Spindles {
            get {
                return ResourceManager.GetString("Spindles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State OFF.
        /// </summary>
        public static string StateOff {
            get {
                return ResourceManager.GetString("StateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot time off.
        /// </summary>
        public static string TimeOff {
            get {
                return ResourceManager.GetString("TimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot time on.
        /// </summary>
        public static string TimeOn {
            get {
                return ResourceManager.GetString("TimeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to Live.
        /// </summary>
        public static string TimeToLive {
            get {
                return ResourceManager.GetString("TimeToLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string Trim {
            get {
                return ResourceManager.GetString("Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typology.
        /// </summary>
        public static string Typology {
            get {
                return ResourceManager.GetString("Typology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this section of the dashboard.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Now.
        /// </summary>
        public static string UntilNow {
            get {
                return ResourceManager.GetString("UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Time.
        /// </summary>
        public static string UsageTime {
            get {
                return ResourceManager.GetString("UsageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User expired.
        /// </summary>
        public static string UserExpired {
            get {
                return ResourceManager.GetString("UserExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manager.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username already exists. Please use a different username.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string UserPassNotValid {
            get {
                return ResourceManager.GetString("UserPassNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted.
        /// </summary>
        public static string UserSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UserSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User  successfully modified.
        /// </summary>
        public static string UserSuccessfullyModify {
            get {
                return ResourceManager.GetString("UserSuccessfullyModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usury.
        /// </summary>
        public static string Usury {
            get {
                return ResourceManager.GetString("Usury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Xmodule/XMU.
        /// </summary>
        public static string XSpindles {
            get {
                return ResourceManager.GetString("XSpindles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools XModule/XMU.
        /// </summary>
        public static string XTools {
            get {
                return ResourceManager.GetString("XTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
