//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bar()
        {
            this.Piece = new HashSet<Piece>();
        }
    
        public int Id { get; set; }
        public string BadAreas { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdOld { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> IsOffcut { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string ProfileCode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string System { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Piece> Piece { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
