//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsonData
    {
        public int Id { get; set; }
        public System.DateTime ElaborationDate { get; set; }
        public bool IsCumulative { get; set; }
        public bool IsElaborated { get; set; }
        public bool IsLoaded { get; set; }
        public string Json { get; set; }
    }
}
