//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine()
        {
            this.CurrentState = new HashSet<CurrentState>();
            this.HistoryBar = new HashSet<HistoryBar>();
            this.HistoryPiece = new HashSet<HistoryPiece>();
            this.HistoryState = new HashSet<HistoryState>();
            this.Piece = new HashSet<Piece>();
            this.StateMachine = new HashSet<StateMachine>();
            this.ToolMachine = new HashSet<ToolMachine>();
            this.HistoryJob = new HashSet<HistoryJob>();
            this.Bar = new HashSet<Bar>();
            this.Spindle = new HashSet<Spindle>();
            this.UserMachineMapping = new HashSet<UserMachineMapping>();
            this.HistoryMessage = new HashSet<HistoryMessage>();
            this.MessageMachine = new HashSet<MessageMachine>();
            this.ParameterMachineValue = new HashSet<ParameterMachineValue>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string FirmwareVersion { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public string KeyId { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<int> MachineModelId { get; set; }
        public Nullable<int> MachineTypeId { get; set; }
        public Nullable<System.DateTime> NextMaintenanceService { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string PlcVersion { get; set; }
        public string Product { get; set; }
        public string ProductVersion { get; set; }
        public string Serial { get; set; }
        public Nullable<System.TimeSpan> Shift1 { get; set; }
        public Nullable<System.TimeSpan> Shift2 { get; set; }
        public Nullable<System.TimeSpan> Shift3 { get; set; }
        public Nullable<double> BarsProductivityGreenThreshold { get; set; }
        public Nullable<double> BarsProductivityYellowThreshold { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<double> OverfeedGreenThreshold { get; set; }
        public Nullable<double> OverfeedYellowThreshold { get; set; }
        public Nullable<double> PiecesProductivityGreenThreshold { get; set; }
        public Nullable<double> PiecesProductivityYellowThreshold { get; set; }
        public Nullable<double> StateProductivityGreenThreshold { get; set; }
        public Nullable<double> StateProductivityYellowThreshold { get; set; }
        public Nullable<double> UTC { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string MachineName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentState> CurrentState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryBar> HistoryBar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryPiece> HistoryPiece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryState> HistoryState { get; set; }
        public virtual MachineModel MachineModel { get; set; }
        public virtual MachineType MachineType { get; set; }
        public virtual Plant Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Piece> Piece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateMachine> StateMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMachine> ToolMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryJob> HistoryJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bar> Bar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spindle> Spindle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMachineMapping> UserMachineMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMessage> HistoryMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageMachine> MessageMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterMachineValue> ParameterMachineValue { get; set; }
    }
}
