//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageMachine()
        {
            this.MessageMachineNotification = new HashSet<MessageMachineNotification>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Params { get; set; }
        public Nullable<System.DateTime> IgnoreDate { get; set; }
        public Nullable<int> MessagesIndexId { get; set; }
    
        public virtual Machine Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageMachineNotification> MessageMachineNotification { get; set; }
        public virtual MessagesIndex MessagesIndex { get; set; }
        public virtual State State { get; set; }
    }
}
