//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterResetValue
    {
        public int Id { get; set; }
        public int ParameterMachineValueId { get; set; }
        public System.DateTime ResetDate { get; set; }
        public Nullable<decimal> ResetValue { get; set; }
        public Nullable<decimal> ValueBeforeReset { get; set; }
    
        public virtual ParameterMachineValue ParameterMachineValue { get; set; }
    }
}
