//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterMachineThreshold
    {
        public int Id { get; set; }
        public int ParameterMachineId { get; set; }
        public int MessageIndexId { get; set; }
        public decimal ThresholdMin { get; set; }
        public decimal ThresholdMax { get; set; }
    
        public virtual ParameterMachine ParameterMachine { get; set; }
        public virtual MessagesIndex MessagesIndex { get; set; }
    }
}
