//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterMachine
    {
        public int Id { get; set; }
        public string ModelCode { get; set; }
        public string VarNumber { get; set; }
        public string HmiLabel { get; set; }
        public Nullable<int> MachineGroup { get; set; }
        public string CnType { get; set; }
        public string CnUm { get; set; }
        public string Keyword { get; set; }
        public string HmiUm { get; set; }
        public string DefaultValue { get; set; }
        public string WLevel { get; set; }
        public string RLevel { get; set; }
        public string HmiSection { get; set; }
        public string LolaLabel { get; set; }
        public string ThresholdMin { get; set; }
        public string ThresholdMax { get; set; }
        public string ThresholdLabel { get; set; }
        public string Panel { get; set; }
        public string Cluster { get; set; }
        public int MachineModelId { get; set; }
        public string Historicized { get; set; }
    
        public virtual MachineModel MachineModel { get; set; }
    }
}
