//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterMachineValue
    {
        public int Id { get; set; }
        public int MachineId { get; set; }
        public int ParameterMachineId { get; set; }
        public string VarNumber { get; set; }
        public Nullable<decimal> VarValue { get; set; }
        public System.DateTime UtcDateTime { get; set; }
        public Nullable<System.DateTime> VariableResetDate { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual ParameterMachine ParameterMachine { get; set; }
    }
}
