//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spindle
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<long> ElapsedTimeWorkTotal { get; set; }
        public Nullable<long> ElapsedTimeWork3K { get; set; }
        public Nullable<long> ElapsedTimeWork6K { get; set; }
        public Nullable<long> ElapsedTimeWork9K { get; set; }
        public Nullable<long> ElapsedTimeWork12K { get; set; }
        public Nullable<long> ElapsedTimeWork15K { get; set; }
        public Nullable<long> ElapsedTimeWork18K { get; set; }
        public Nullable<long> ExpectedWorkTime { get; set; }
        public Nullable<int> WorkOverheatingCount { get; set; }
        public Nullable<int> WorkOverPowerCount { get; set; }
        public Nullable<int> WorkOverVibratingCount { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<System.DateTime> ReplacedDate { get; set; }
        public string Serial { get; set; }
        public Nullable<int> ToolChangedCount { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
