//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMachine
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<long> ElapsedTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> OperatorLevel { get; set; }
        public string Operator { get; set; }
        public Nullable<double> Overfeed { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
