//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FomMonitoringCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMachineMapping
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int MachineId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
